---

- name: Deploy {{ application_name }} codebase in production
  hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: False
  vars:
    setup_git_repo: yes  # set to no for local development and map your local git repo in the Vagrantfile instead
    setup_local_repo: no
    update_apt_cache: yes
    ansible_ssh_private_key_file: "/Users/macos/Downloads/group2.pem"
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml

  roles:
    - base
