---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  remote_user: vagrant 
  gather_facts: False
  vars:
    setup_git_repo: yes  # set to no for local development and map your local git repo in the Vagrantfile instead
    setup_local_repo : yes
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/development.yml

  roles:
    - base
    