---

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: install python 3
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)

- name: Install base packages needed for scanner la
  apt: 
     name={{item}}
     state=installed 
     update_cache={{ update_apt_cache }}
  with_items:
          - build-essential
          - git
          - python-pip
          - unzip

- name: Install spider dependencies using pip
  pip:
    name={{item}}
  with_items:
    - scrapy
    - bs4
    - requests

- name: Git clone our awesome scanner
  git:
    repo: 'https://github.com/CS5331-G2/assign3.git'
    dest: /home/vagrant/assign3
    version: master
  when: setup_git_repo is defined and setup_git_repo

- name: Copy html.zip to /home/vagrant
  copy:
    src: /Users/macos/Dropbox (Personal)/1. NUS/SourceCode/CS5331/assign3/html.zip
    dest: /home/vagrant
  when: setup_local_repo is defined and setup_local_repo

# - name: Unzip html.zip
#   unarchive: 
#     src: /home/vagrant/html.zip
#     dest: /home/vagrant/

# - name: Install html.zip setup.sh
#   command: ./home/vagrant/html/setup.sh